### ISSUE TITLE
Custom .scss file

### ISSUE THREAD

**Issue by anthonybudd** [Splode/jekyll-vue-template#6]
If I want to add a .scss file to this project where and how would I go about including that so it gets compiled correctly?

**Comment by Splode** [comment]
You can place it wherever you'd like. The convention is to place `.scss` files in a `_sass` directory in the project root and import them via a `main.scss` file in a `css` directory. Jekyll supports Sass out of the box, but to have Jekyll compile it, you'll need to add a pair of triple dashes to the beginning of the file like so:

```scss
---
---

.whatever {
  margin: auto;
  // etc.
}
```

Jekyll has a an example project structure illustrating this concept: [https://github.com/jekyll/jekyll-sass-converter/tree/master/docs](https://github.com/jekyll/jekyll-sass-converter/tree/master/docs)

You can read more about how Jekyll handles Sass and how to customize that behavior on their documentation for assets: [https://jekyllrb.com/docs/assets/](https://jekyllrb.com/docs/assets/)
